goblin: 
        party_weight: 1.25
        type: humanoid 
        typename: goblin
        wslots: 1
        attacks: 1
        level_min: 1
        level_max: 2
        alignment: neutral
orc:    
        agility: 9
        THAC0: 19
        base_ap: 1
        base_hp: 8
        party_weight: 1.5
        type: humanoid
        typename: orc
        wslots: 1
        attacks: 1
        level_min: 1
        level_max: 2
        alignment: evil
ant:    
        agility: 9
        THAC0: 20
        AC: 80
        base_ap: 1 
        base_hp: 1 
        party_weight: 1
        type: Insect 
        unconfirmed_name: Wriggling Object
        unconfirmed_name_plural: Wriggling Objects
        typename: Ant
        wslots: 1 
        attacks: 1 
        level_min: 1
        level_max: 1
        alignment: neutral
        attack_a: pincer
        spells: none
