# All monster data for combat.

ant:
    unconfirmed_name: Wriggling Object
    unconfirmed_name_plural: Wriggling Objects
    level: 1
    type: Insectoid
    typename: Ant
    hp: [1, 1]
    ac: 80
    attacks:
        bite:
            dmg: [1, 1]
    s_attacks: None
    spells: None
    breath: None
    specials:
        call:
            chance: 50
    resists: None
    weaknesses:
        - Sleep
        - Silence
        - Charm
    friendly: 0
    xp_win: 40
    group_total: [3, 9]
toad:
    unconfirmed_name: Wriggling Object
    unconfirmed_name_plural: Wriggling Objects
    level: 1
    type: Amphibious
    typename: Toad
    hp: [2, 4]
    ac: 50
    attacks:
        lick:
            dmg: [1, 1]
        kick:
            dmg: [1, 1]
    s_attacks: None
    spells: None
    breath: None
    specials:
        escape:
            chance: 10
    resists: None
    weaknesses:
        - Sleep
        - Silence
    friendly: 0
    xp_win: 120
    group_total: [2, 8]
